<a href="https://colab.research.google.com/github/uellington-bonaparte/dotfiles/blob/master/Apreensoes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd
import seaborn as sns

In [36]:
from google.colab import files
# uploaded = files.upload()

# carrega o arquivo de apreensões (fonte: bi.pf.gov.br > Estatísticas > Apreensões-Analítico)
# path_apreensoes = '/content/apreensoes_pf.xlsx'
# path_apreensoes = '/content/apreensoes_pf.zip'
path_apreensoes = '/content/sample_data/apreensoes_pf.csv'

# pd.read_excel(path_apreensoes, nrows = 100).info
# pd.read_csv(path_apreensoes, nrows = 100, sep=';', na_values='-', encoding='latin1', usecols=[5,10,11,12,13,14])
pd.read_csv(path_apreensoes, sep=';', na_values='-', encoding='latin1', usecols=[5,9, 10,11,12,13,14])
# pd.read_csv(path_apreensoes, sep=';', na_values='-', encoding='latin1').info()

       UF Apreensão N° Apreensão  ... Valor Estimado Qtde Apreensão
0                SP     160/2013  ...            NaN            191
1                SP    2274/2013  ...            NaN            260
2                SP       1/2000  ...            NaN              1
3                AL     603/2010  ...            NaN           4135
4                AL     603/2010  ...            NaN              1
...             ...          ...  ...            ...            ...
294007           SP     861/2019  ...    R$ 20000,00          20000
294008           SP     865/2019  ...    R$ 21100,00          21100
294009           SP     865/2019  ...    R$ 21100,00          21100
294010           SP     865/2019  ...    R$ 21100,00          21100
294011           SP     852/2019  ...            NaN              1

[294012 rows x 7 columns]

https://www.ibge.gov.br/estatisticas/sociais/populacao/9103-estimativas-de-populacao.html?=&t=resultados